"use client";
import { Toaster } from "@/components/ui/sonner";
import { Outfit } from "next/font/google";
import { usePathname } from "next/navigation";
import Header from "./_components/Header";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Green Basket",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname();
  const showHeader =
    params == "/sign-in" || params == "/create-account" ? false : true;
  return (
    <html lang="en">
      <body className={outfit.className}>
        {showHeader && <Header />}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
