import { Toaster } from "@/components/ui/sonner";
import { Outfit } from "next/font/google";
import Header from "./_components/Header";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Green Basket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Header />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
